apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: roboshop  # namespace in which pod to be created
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80

# kubectl apply -f <pod-file-name>.yaml
#kubectl get pods
#kubectl get pods -o wide
#kubectl get pods -o yaml
#kubectl get pods -n roboshop # it lists the pods in roboshop namespace
#kubectl get pods -A # lists all the pods in all namespaces