---
apiVersion: v1
kind: Pod
metadata:
  name: multi
spec:
  containers:
  - image: nginx
    name: nginx
    Ports:
      containerPort: 80
  - image: almalinux
    name: almalinux
    command: ["sleep","200"]