apiVersion: v1
kind: Pod
metadata:
  name: labels-pod
  labels:
    course: k8s
    duration: 25hrs
  annotations:
    org.docker.kubernetes.image:dd
spec:
  containers:
  - image: nginx
    name: nginx
    Ports:
    - containerPort: 80