apiVersion: v1
kind: Pod
metadata: 
  name: stress-pod
spec:
  containers:
  - name: stress
    image: stress
    command: ["sleep","200"]

#Run below stress command to exhaust cpu in the server if no limit resources defined.

# $kubectl create -f 08-no-res-limit-stress.yaml
# $kubectl get pods
# $kubectl get pods -o wide
# $kubectl exec -it stress -- bash
#     #stress-ng --cpu 1

# kubectl describe pod stress - this command provides in which node this pod is running to check the CPU utilixation.

#make sure stress image is available 
# dockerfile to create stress image
# FROM almalinux
# RUN yum update -y
# RUN yum install stress ng -y
# CMD["stress-ng","-help"]

# $docker build -t stress .