---
apiVersion: v1
kind: LimitRange
metadata:   
  name: cpu-resource-constraint
spec:
  limits:  # # default limits
  - default: 
      cpu: "500m" 
    defaultRequest:   # default request
      cpu: "500m"
    # max & min cpu limit range
    max:  
      cpu: "1"
    min:
      cpu: 100m
    type: Container

---
apiVersion: v1
kind: Pod
metadata:
  name: limit-res-pod
spec:
  containers:
  - name: nginx
    image: nginx
    # resources:
    #   requests:
    #     memory: "64Mi"
    #     cpu: "250m" # 1cpu = 1000m
    #   limits:
    #     memory: "128Mi"
    #     cpu: "500m"

---